export const lightTokens: Record<string, string> = {
  background: '#ffffff',
  foreground: '#0a0a0a',
  card: '#ffffff',
  cardForeground: '#0a0a0a',
  popover: '#ffffff',
  popoverForeground: '#0a0a0a',
  primary: '#171717',
  primaryForeground: '#fafafa',
  secondary: '#f5f5f5',
  secondaryForeground: '#171717',
  muted: '#f5f5f5',
  mutedForeground: '#737373',
  accent: '#f5f5f5',
  accentForeground: '#171717',
  destructive: '#ef4444',
  destructiveForeground: '#fafafa',
  success: '#22c55e',
  successForeground: '#fafafa',
  warning: '#f59e0b',
  warningForeground: '#fafafa',
  info: '#3b82f6',
  infoForeground: '#fafafa',
  border: '#e5e5e5',
  input: '#e5e5e5',
  ring: '#a3a3a3',
  radius: '6px',
}

export const darkTokens: Record<string, string> = {
  background: '#0a0a0a',
  foreground: '#fafafa',
  card: '#0a0a0a',
  cardForeground: '#fafafa',
  popover: '#0a0a0a',
  popoverForeground: '#fafafa',
  primary: '#fafafa',
  primaryForeground: '#0a0a0a',
  secondary: '#262626',
  secondaryForeground: '#fafafa',
  muted: '#262626',
  mutedForeground: '#a3a3a3',
  accent: '#262626',
  accentForeground: '#fafafa',
  destructive: '#dc2626',
  destructiveForeground: '#fafafa',
  success: '#16a34a',
  successForeground: '#fafafa',
  warning: '#d97706',
  warningForeground: '#fafafa',
  info: '#2563eb',
  infoForeground: '#fafafa',
  border: '#262626',
  input: '#262626',
  ring: '#525252',
  radius: '6px',
}
